spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # This tells Spring to print SQL queries to the console (great for learning!)
  sql:
    init:
      mode: always

  kafka:
    # Pulls the Aiven 'Service URI' from your deployment environment
    bootstrap-servers: ${KAFKA_URL}
    ssl:
      trust-store-location: classpath:client.truststore.jks
      trust-store-password: secret
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: SCRAM-SHA-256
      sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: smarthire-ai-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true              

  cache:
    redis:
      time-to-live: 600000ms     

openai:
  api:
    key: ${OPENAI_API_KEY}
  model: gpt-5.4-mini

jwt:
  secret: ${JWT_SECRET}

server:
  port: ${PORT:8080}