spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  datasource:
    # Notice we changed 'postgresql://' to 'jdbc:postgresql://' so Java understands it
    url: jdbc:postgresql://ep-dry-resonance-ataz0j8h.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: change-me
    driver-class-name: org.postgresql.Driver

  # This tells Spring to print SQL queries to the console (great for learning!)
  sql:
    init:
      mode: always

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: smarthire-ai-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true              

  cache:
    redis:
      time-to-live: 600000ms     

openai:
  api:
    key: change-me
  model: gpt-5.4-mini